name: Push Verify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Push Verify
    uses: jacobeicher/ReusableWorkflows/.github/workflows/reusable-build.yml@main
    with:
      dotnet_version: 9.0.x